/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Visual;
import Logic.Control;

/**
 *
 * @author Maria Valentina Soto
 */
public class Interfaz extends javax.swing.JFrame {
    
    private Control app;

    /**
     * Creates new form Interfaz
     */
    public Interfaz(Control app) {
        this.app = app;
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelApp = new javax.swing.JPanel();
        btnSalir = new javax.swing.JButton();
        labelBackg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1000, 714));
        setUndecorated(true);
        setResizable(false);

        jPanelApp.setMaximumSize(new java.awt.Dimension(1000, 714));
        jPanelApp.setMinimumSize(new java.awt.Dimension(1000, 714));
        jPanelApp.setPreferredSize(new java.awt.Dimension(1000, 714));
        jPanelApp.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnSalir.setBackground(new java.awt.Color(255, 51, 51));
        btnSalir.setFont(new java.awt.Font("Tw Cen MT", 1, 12)); // NOI18N
        btnSalir.setForeground(new java.awt.Color(255, 255, 255));
        btnSalir.setText("SALIR");
        btnSalir.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        jPanelApp.add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 0, 60, 30));

        labelBackg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Segundo Proyecto Sistemas Operativos.jpg"))); // NOI18N
        jPanelApp.add(labelBackg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 714));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelApp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelApp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnSalirActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSalir;
    private javax.swing.JPanel jPanelApp;
    private javax.swing.JLabel labelBackg;
    // End of variables declaration//GEN-END:variables
}
